# Generated by Django 4.1 on 2022-09-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available_status',
            field=models.BooleanField(default=True),
        ),
    ]
