# Generated by Django 4.1 on 2022-09-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_books_available_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='email_id',
        ),
    ]
